### ISSUE TITLE
No such Session

### ISSUE THREAD

**Issue by AvramM** [StephenCleary/BrowserBoss#2] opened 2015-10-30 03:07 UTC
Our unit tests are failing on some machines and passing on others. When they fail, they fail with:

InvalidOperationException: no such session

Any idea what might cause that? It has chrome and the latest Chrome Driver installed.

**Comment by StephenCleary** [comment] 2015-10-30 21:10
I have not seen this behavior.

However, I don't use BrowserBoss for unit testing. It wasn't really designed for that (though it could be used for it).

Do you have a stack trace?

**Comment by AvramM** [comment] 2015-11-02 10:06
During the test, Chrome opens and the page loads successfully. When Chrome
closes, the test fails. This is the StackTrace:

at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response
errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String
driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String
attributeName)
at Nito.BrowserBoss.Element.ToString()

**Comment by AvramM** [comment] 2015-12-14 03:30
I updated Selenium and ran it again, the mode of failure has now changed. I added a project demonstrating the failure.

https://github.com/AvramM/BrowserBossIssue

But basically it fails at the first hurdle:

```
Boss.Url = "https://ipleak.net";
```

![screenshot](https://cloud.githubusercontent.com/assets/15082147/11772275/e6001c50-a255-11e5-8820-9d9b67c845e9.png)

**Comment by StephenCleary** [comment] 2015-12-16 02:48
I'm not able to reproduce this on my machine; the test app ran fine.

Things to check off the top of my head:
- Are some of your VS instances running as administrator and others not?
- Is there anything else already on that port?

**Comment by StephenCleary** [comment] 2016-04-15 01:21
Closing due to lack of repro.

**Closed as completed by StephenCleary** 2016-04-15 01:21 UTC
