### ISSUE TITLE
Boss.Find() throws exception

### ISSUE THREAD

**Issue by dlwiii** [StephenCleary/BrowserBoss#3] opened 2015-12-11 03:33 UTC
When running in VS2013, the Find method throws, nags me,  then ignores an exception:

unknown error: Syntax error, unrecognized expression: //table[contains(@class,'item_list')]/tbody
  (Session info: chrome=47.0.2526.80)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 6.3 x86_64)

The call works fine though!  Why do we get this message?

**Comment by StephenCleary** [comment] 2015-12-16 02:17
One of the primary problems with Selenium that people encounter is that it's not very reliable. It tends to throw exceptions, particularly when the page is still loading (or dynamically building itself _after_ loading, very common in SPAs).

For this reason, BrowserBoss will retry its operations by default. It will retry for up to 30 seconds, and (I'm pretty sure) will delay a second or so between retries. This is usually sufficient time for the page to fully realize itself and the call to succeed.

However, if you run this _in_ Visual Studio, it can break when those exceptions are thrown. BrowserBoss catches the exception and automatically retries - causing the `Find` method to ultimately succeed. But the exceptions are actually being thrown and caught, by design.

I do find it interesting though that the exception is a syntax error; this is not a kind of exception that I would expect from, say, a partially-loaded page. Do you have a (simplified) HTML document that I can repro this with?

**Comment by StephenCleary** [comment] 2016-04-15 01:21
Closing due to lack of repro.

**Closed as completed by StephenCleary** 2016-04-15 01:21 UTC
